apiVersion: v1
kind: Service
metadata:
  name: dna-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: dna
  ports:
  - port: 3000
    nodePort: 30006
---
apiVersion: v1
kind: Service
metadata:
  name: dna-db-entrypoint
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
